#Generated by scaffolding
class CreateBooks < ActiveRecord::Migration
  def change
    create_table :books do |t|
      #Validations added after table creation
      t.string :title, :null => false
      t.string :author, :null => false
      t.string :genre, :null => false
      t.string :publisher, :null => false
      t.string :date, :null => false
      t.string :location, :null => false

      t.timestamps
    end
  end
end
